version: '3.7'
services:
  runner:
    build: .
    volumes:
      - ./mount_point/opt/idea:/opt/idea
      - ./mount_point/home/default:/home/default
      - ./mount_point/var/tmp/docker-entrypoint.sh:/var/tmp/docker-entrypoint.sh
      - ./mount_point/etc/supervisord.conf:/etc/supervisord.conf
      - ./:/mnt/working
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USER_HOME
      - USER_NAME
      - USER_ID
      - GROUP_ID
      - GROUP_ID_DOCKER
      - DISPLAY
    working_dir: /mnt/working
    privileged: true

