version: '3.7'
services:
  runner:
    build: .
    volumes:
      - ./mount_point/opt/idea:/opt/idea
      - ./mount_point/home/default:/home/default
      - ./:/mnt/working
    environment:
      - USER_HOME
      - USER_NAME
      - USER_ID
      - GROUP_ID
      - DISPLAY
    working_dir: /mnt/working


